"""Added gallery column to Pilgrimage model

Revision ID: 3212b0d87164
Revises: eee6b84ac33e
Create Date: 2025-03-27 20:08:24.186107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3212b0d87164'
down_revision = 'eee6b84ac33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilgrimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('virtual_tour_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('helpful_votes', sa.Integer(), nullable=True))

    with op.batch_alter_table('trip_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('itinerary', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('language')
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('trip_plan', schema=None) as batch_op:
        batch_op.drop_column('itinerary')
        batch_op.drop_column('status')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('helpful_votes')
        batch_op.drop_column('images')

    with op.batch_alter_table('pilgrimage', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('virtual_tour_url')
        batch_op.drop_column('featured')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('gallery')

    # ### end Alembic commands ###
