"""Add payment_method to trip_plan

Revision ID: c11d970bf810
Revises: 3212b0d87164
Create Date: 2025-03-29 10:33:01.428039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11d970bf810'
down_revision = '3212b0d87164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_comment')
    op.drop_table('saved_pilgrimage')
    op.drop_table('travel_log')
    op.drop_table('forum_category')
    op.drop_table('travel_tip')
    op.drop_table('forum_post')
    op.drop_table('payment')
    with op.batch_alter_table('pilgrimage', schema=None) as batch_op:
        batch_op.drop_column('virtual_tour_url')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('trip_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('refund_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refund_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accommodation_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transportation_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('guide_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('trip_plan', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('guide_fee')
        batch_op.drop_column('transportation_fee')
        batch_op.drop_column('accommodation_fee')
        batch_op.drop_column('base_price')
        batch_op.drop_column('refund_requested_at')
        batch_op.drop_column('refund_details')
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('pilgrimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('virtual_tour_url', sa.VARCHAR(length=200), nullable=True))

    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('trip_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['trip_plan_id'], ['trip_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['forum_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_tip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pilgrimage_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pilgrimage_id'], ['pilgrimage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('images', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_pilgrimage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pilgrimage_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pilgrimage_id'], ['pilgrimage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
